# Numpy Tricks

In [9]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [10]:
arr = np.array([2,4,6])
arr

array([2, 4, 6])

#### Create one's matrics

In [5]:
oneMatrics = np.ones([2,3])
oneMatrics

array([[1., 1., 1.],
       [1., 1., 1.]])

#### Create Zero's metrics

In [6]:
np.zeros([4,5],dtype = 'int32')

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

#### Arrange Function

In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Tile
- we use in this format np.tile(2,[3,4]), and it's mean, create an array that have 3 rows and 4 columns and fill it with 2,

In [8]:
np.tile(2,[3,4])

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

### Repeat Function:
-  it works in this format, np.repeat([2,3],2), it give an array in the first argument and repeat the number you put in the second argument.

In [11]:
np.repeat([3,4],2)

array([3, 3, 4, 4])

### Linspace function
- we use this function in this format:
    - np.linspace(1,5,10)
    - and it means create an array between 1 and 5 which have 10 argument

In [12]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

## BradCasting
- why we need to do it with numpy bradCasting function?
- Because if:
   -  we have this tow array to add or subtract or another operation
      - arr1 = np.array([1,3,5,7,9])
      - arr2 = np.array([2,4,6,8,0])
   - if I use the Loop it not change matter lots in this format
   - but what about the 3k array element
   - we use numpy bradCasting method to add the speed of operation

In [13]:
arr1 = np.array([1,3,5,7,9])
arr2 = np.array([2,4,6,8,10])

In [14]:
arr1 + arr2

array([ 3,  7, 11, 15, 19])

In [15]:
arr1 - arr2

array([-1, -1, -1, -1, -1])

In [16]:
arr1 * arr2

array([ 2, 12, 30, 56, 90])

In [17]:
arr1 // arr2

array([0, 0, 0, 0, 0])

In [18]:
arr1 % arr2

array([1, 3, 5, 7, 9])