# Numpy Tricks

In [9]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [10]:
arr = np.array([2,4,6])
arr

array([2, 4, 6])

#### Create one's matrics

In [5]:
oneMatrics = np.ones([2,3])
oneMatrics

array([[1., 1., 1.],
       [1., 1., 1.]])

#### Create Zero's metrics

In [6]:
np.zeros([4,5],dtype = 'int32')

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

#### Arrange Function

In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Tile
- we use in this format np.tile(2,[3,4]), and it's mean, create an array that have 3 rows and 4 columns and fill it with 2,

In [8]:
np.tile(2,[3,4])

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

### Repeat Function:
-  it works in this format, np.repeat([2,3],2), it give an array in the first argument and repeat the number you put in the second argument.

In [11]:
np.repeat([3,4],2)

array([3, 3, 4, 4])